export type GovukTextWidthClass =
  | 'govuk-!-width-full'
  | 'govuk-!-width-three-quarters'
  | 'govuk-!-width-two-thirds'
  | 'govuk-!-width-one-half'
  | 'govuk-!-width-one-third'
  | 'govuk-!-width-one-quarter'
  | 'govuk-input--width-20'
  | 'govuk-input--width-10'
  | 'govuk-input--width-5'
  | 'govuk-input--width-4'
  | 'govuk-input--width-3'
  | 'govuk-input--width-2';

export type HTMLInputType =
  | 'button'
  | 'checkbox'
  | 'color'
  | 'date'
  | 'datetime-local'
  | 'email'
  | 'file'
  | 'hidden'
  | 'image'
  | 'month'
  | 'number'
  | 'password'
  | 'radio'
  | 'range'
  | 'reset'
  | 'search'
  | 'submit'
  | 'tel'
  | 'text'
  | 'time'
  | 'url'
  | 'week';
